### ISSUE TITLE
Consider upgading `Ingress` API Version from `extensions/v1beta1` to `networking.k8s.io/v1`

### ISSUE THREAD

**Issue by serejke** [axonweb3/axon-devops#146]
https://github.com/axonweb3/axon-devops/blob/05d46fec5af8fb3525f56a47fde53204127fe111/k8s-deploy/k8s/ingress/axon-ingress.yaml#L1

`extensions/v1beta1` is [deprecated](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) and should be replaced by `networking.k8s.io/v1`.

The `networking.k8s.io/v1` has a slightly different configuration, for example:

```
    - path: /
      backend:
        serviceName: axon1
        servicePort: 8100
```

should be replaced with:
```
    - path: /
      pathType: Prefix      
      backend:
        service:
          name: axon1
          port:
              number: 8100
```
